import type { Metadata } from "next";
import Link from "next/link";
import SiteFooter from "@/components/SiteFooter";
import PublicHeader from "@/components/PublicHeader";
import { Card, Badge } from "@/components/ui";

export const metadata: Metadata = {
  title: "Invest in the Senior-Marketing Arbitrage Engine — medigap.plus",
  description:
    "Deposit capital that's deployed as the next dollar in line across a proven senior-marketing engine. 50% profit share, 2% management fee, real-time statements. Accredited investors only.",
};

const howItWorks = [
  ["1", "Deposit capital", "Fund your account. Your capital joins the queue and is deployed as the next dollar in line — it goes to work buying high-intent senior traffic, not sitting idle."],
  ["2", "We run the arbitrage", "We spend that capital acquiring calls and leads, then monetize them across our network of bidding agents, carriers and advertisers — the same engine that produced 36,000 calls and 100,000 leads last year."],
  ["3", "Share the profit", "You receive 50% of the profit your deployed capital generates, net of a 2% management fee, with real-time statements showing exactly how every dollar performed."],
];

const terms = [
  ["50% profit share", "You keep half of the net profit generated by your deployed capital."],
  ["2% management fee", "A simple 2% management fee — we only win big when you do."],
  ["Real-time statements", "Watch deployment, revenue and profit update live in your investor dashboard."],
  ["Accredited only", "Participation is limited to verified accredited investors."],
];

export default function Page() {
  return (
    <>
      <PublicHeader />

      <section className="relative overflow-hidden">
        <div className="absolute inset-0 brand-gradient opacity-[0.07]" />
        <div className="mx-auto max-w-7xl px-6 py-16 md:py-24 relative">
          <Badge tone="gold">Accredited Investors Only</Badge>
          <h1 className="mt-5 text-4xl md:text-6xl font-extrabold leading-tight max-w-4xl">
            Invest in a senior-marketing <span className="text-gradient">arbitrage engine.</span>
          </h1>
          <p className="mt-5 text-lg text-[var(--muted)] max-w-2xl">
            We turn marketing dollars into high-intent senior calls and leads, then sell them to a marketplace of
            bidding agents, carriers and advertisers. Your capital is deployed as the next dollar in line — and you
            share in the profit.
          </p>
          <div className="mt-7 flex flex-wrap gap-3">
            <Link href="/login" className="btn btn-brand text-base">Open investor account →</Link>
            <Link href="/contact" className="btn btn-ghost text-base">Request the deck</Link>
          </div>
          <p className="mt-4 text-xs text-[var(--muted)]">Available to verified accredited investors only.</p>
        </div>
      </section>

      {/* Thesis */}
      <section className="mx-auto max-w-7xl px-6 py-12">
        <div className="card glow p-8 md:p-10 relative overflow-hidden">
          <div className="absolute inset-0 brand-gradient opacity-[0.06]" />
          <div className="relative grid md:grid-cols-2 gap-8 items-center">
            <div>
              <h2 className="text-2xl md:text-3xl font-bold">The thesis: <span className="text-gradient">$1 in → ~$3 out.</span></h2>
              <p className="mt-4 text-[var(--muted)]">
                Senior insurance and care are some of the highest-value verticals in all of lead generation. We've
                spent years building the audience, the routing technology and the buyer marketplace. The result is a
                repeatable arbitrage: every dollar we deploy into senior traffic tends to come back as roughly three —
                and your capital rides that spread.
              </p>
            </div>
            <div className="grid grid-cols-3 gap-4 text-center">
              <div><div className="text-3xl md:text-4xl font-extrabold text-gradient">36,000</div><div className="mt-1 text-xs text-[var(--muted)]">calls last year</div></div>
              <div><div className="text-3xl md:text-4xl font-extrabold text-gradient">100,000</div><div className="mt-1 text-xs text-[var(--muted)]">leads last year</div></div>
              <div><div className="text-3xl md:text-4xl font-extrabold text-[var(--gold)]">~3x</div><div className="mt-1 text-xs text-[var(--muted)]">target $ in → $ out</div></div>
            </div>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="mx-auto max-w-7xl px-6 py-6">
        <h2 className="text-2xl md:text-3xl font-bold text-center">How it works</h2>
        <div className="mt-8 grid gap-4 md:grid-cols-3">
          {howItWorks.map(([n, title, body]) => (
            <Card key={title}>
              <div className="text-2xl font-extrabold text-gradient">{n}</div>
              <h3 className="mt-2 font-semibold text-lg">{title}</h3>
              <p className="mt-1 text-sm text-[var(--muted)]">{body}</p>
            </Card>
          ))}
        </div>
      </section>

      {/* Terms */}
      <section className="mx-auto max-w-7xl px-6 py-12">
        <h2 className="text-2xl md:text-3xl font-bold text-center">The terms</h2>
        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {terms.map(([title, body]) => (
            <Card key={title}>
              <h3 className="font-semibold">{title}</h3>
              <p className="mt-2 text-sm text-[var(--muted)]">{body}</p>
            </Card>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-6 py-14">
        <div className="card glow p-8 md:p-12 text-center relative overflow-hidden">
          <div className="absolute inset-0 brand-gradient opacity-[0.08]" />
          <div className="relative">
            <h2 className="text-2xl md:text-4xl font-extrabold">Put your capital next in line</h2>
            <p className="mt-3 text-[var(--muted)] max-w-2xl mx-auto">
              Open an investor account to review full terms, complete accreditation, and fund your first deployment —
              with real-time statements from day one.
            </p>
            <div className="mt-7 flex flex-wrap gap-3 justify-center">
              <Link href="/login" className="btn btn-brand text-lg">Open investor account →</Link>
            </div>
            <p className="mt-5 text-xs text-[var(--muted)] max-w-2xl mx-auto">
              This page is for informational purposes only and is not an offer to sell or a solicitation of an offer to
              buy any security. Investments are available to verified accredited investors only and involve risk,
              including the possible loss of capital. Past performance does not guarantee future results.
            </p>
          </div>
        </div>
      </section>

      <SiteFooter />
    </>
  );
}
