#!/usr/bin/env bash
#
# add-domain.sh — make a launched white-label marketing site LIVE on the production host.
#
# Launching a site in the back office only creates its Site row in the database.
# For a brand-new domain (e.g. parentingupward.org) to actually serve over HTTPS,
# the production nginx in front of the Next.js app needs a vhost + a TLS certificate
# for that exact domain. Without it, requests fall through to the default
# medigap.plus vhost (wrong cert -> browser SSL error; Host rewritten -> the app
# shows default medigap.plus branding instead of the site).
#
# This script adds the nginx vhost (forwarding the REAL Host header so the app can
# resolve the site by hostname) and issues a Let's Encrypt cert. Run it ON the
# production server (137.220.56.129), once per new domain.
#
# Prereqs (one-time): the domain's DNS A record must already point at this server,
# nginx + certbot installed, and the Next app running on $UPSTREAM.
#
# Usage:
#   sudo ./scripts/add-domain.sh parentingupward.org
#   sudo ./scripts/add-domain.sh parentingupward.org 127.0.0.1:3000 ops@medigap.plus
#
set -euo pipefail

DOMAIN="${1:?Usage: add-domain.sh <domain> [upstream host:port] [letsencrypt email]}"
UPSTREAM="${2:-127.0.0.1:3020}"   # where the Next.js app (pm2 "medigap") listens on prod
EMAIL="${3:-ops@medigap.plus}"    # Let's Encrypt account email
DOMAIN="$(echo "$DOMAIN" | tr '[:upper:]' '[:lower:]' | sed 's#^https\?://##; s#/.*$##')"
AVAIL="/etc/nginx/sites-available/${DOMAIN}.conf"
ENABLED="/etc/nginx/sites-enabled/${DOMAIN}.conf"

echo "==> Checking DNS for ${DOMAIN} …"
if command -v dig >/dev/null 2>&1; then
  RESOLVED="$(dig +short "$DOMAIN" | tail -1 || true)"
  SELF="$(curl -s --max-time 5 https://api.ipify.org || true)"
  echo "    ${DOMAIN} -> ${RESOLVED:-<none>}   this server -> ${SELF:-unknown}"
  if [ -n "$RESOLVED" ] && [ -n "$SELF" ] && [ "$RESOLVED" != "$SELF" ]; then
    echo "    WARNING: DNS does not point here yet. Add an A record ${DOMAIN} -> ${SELF} first."
    echo "    Certbot will fail until DNS propagates. Continue anyway? (Ctrl-C to abort)"; sleep 5
  fi
fi

echo "==> Writing nginx vhost ${AVAIL}"
cat > "$AVAIL" <<NGINX
# Auto-generated by scripts/add-domain.sh for white-label site ${DOMAIN}.
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};

    # Allow certbot's HTTP-01 challenge.
    location /.well-known/acme-challenge/ { root /var/www/html; }

    location / {
        proxy_pass http://${UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        # CRITICAL: forward the real hostname so the app resolves the right Site.
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX

ln -sf "$AVAIL" "$ENABLED"

echo "==> Testing & reloading nginx (HTTP vhost)"
nginx -t
systemctl reload nginx

echo "==> Issuing Let's Encrypt certificate (adds TLS + forces HTTPS redirect)"
certbot --nginx -d "$DOMAIN" -d "www.${DOMAIN}" \
  --non-interactive --agree-tos -m "$EMAIL" --redirect

echo "==> Final nginx reload"
nginx -t && systemctl reload nginx

echo ""
echo "✅ ${DOMAIN} is live. Verify:"
echo "   curl -sI https://${DOMAIN} | head -1        # expect HTTP/.. 200"
echo "   curl -s https://${DOMAIN} | grep -o '<title>[^<]*</title>'   # expect the site's name"
echo ""
echo "If it still shows medigap.plus branding, confirm the Site row exists and is"
echo "active in the production database (back office → Marketing Sites → toggle Active)."
