import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import PrintButton from "@/components/PrintButton";

export const dynamic = "force-dynamic";

export default async function BrandKit({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const app = await db.partnerApplication.findUnique({ where: { id } });
  if (!app) notFound();
  const colors = (app.brandColors || "#0b5,#1e63d6,#16d6a5").split(/[\s,]+/).filter(Boolean).slice(0, 6);
  const primary = colors[0] || "#16d6a5";

  return (
    <div className="max-w-3xl mx-auto">
      <div className="flex items-center justify-between mb-4 print:hidden">
        <h1 className="text-xl font-bold">Brand Guidelines — {app.businessName}</h1>
        <PrintButton />
      </div>

      <div className="bg-white text-[#111] rounded-2xl overflow-hidden shadow print:shadow-none">
        {/* Cover */}
        <div className="p-10" style={{ background: `linear-gradient(120deg, ${colors[0] || "#16d6a5"}, ${colors[1] || "#1e8bff"})` }}>
          {app.logoUrl ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={app.logoUrl} alt="logo" className="h-16 mb-6 bg-white/90 rounded p-2" />
          ) : <div className="text-3xl font-black text-white">{app.businessName}</div>}
          <div className="text-white/90 text-sm mt-2">Brand Guidelines</div>
          <div className="text-white/70 text-xs mt-1">{app.website || ""}</div>
        </div>

        <div className="p-10 space-y-8">
          <section>
            <h2 className="text-lg font-bold border-b pb-2 mb-3">Logo</h2>
            {app.logoUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={app.logoUrl} alt="logo" className="h-14" />
            ) : <p className="text-sm text-gray-500">Wordmark: <b style={{ color: primary }}>{app.businessName}</b>. Keep clear space equal to the cap-height on all sides; never stretch or recolor.</p>}
          </section>

          <section>
            <h2 className="text-lg font-bold border-b pb-2 mb-3">Color palette</h2>
            <div className="flex flex-wrap gap-4">
              {colors.map((c) => (
                <div key={c} className="text-center">
                  <div className="w-20 h-20 rounded-lg border" style={{ background: c }} />
                  <div className="text-xs mt-1 font-mono">{c}</div>
                </div>
              ))}
            </div>
            <p className="text-xs text-gray-500 mt-3">Primary <b>{colors[0]}</b> for CTAs and key accents. Secondary for support and links. Keep contrast AA for body text.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold border-b pb-2 mb-3">Typography</h2>
            <p style={{ fontFamily: "Arial, Helvetica, sans-serif" }} className="text-2xl font-extrabold">Headlines — Geist / Arial Bold</p>
            <p style={{ fontFamily: "Arial, Helvetica, sans-serif" }} className="text-base text-gray-700">Body — clean sans-serif, 16px, 1.5 line-height. Senior-friendly: large, high contrast, generous spacing.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold border-b pb-2 mb-3">Voice & messaging</h2>
            <p className="text-sm text-gray-700">Warm, trustworthy, local. Lead with savings and real human help. Primary CTA: <b>{app.primaryCta === "form" ? "Get my free quote" : "Call now — talk to a licensed specialist"}</b>.</p>
            {app.moneyWords && <p className="text-sm text-gray-700 mt-2">Emphasize: <b>{app.moneyWords}</b>.</p>}
            {app.usp && <p className="text-sm text-gray-700 mt-2">Differentiators: {app.usp}</p>}
          </section>

          <section>
            <h2 className="text-lg font-bold border-b pb-2 mb-3">Usage</h2>
            <ul className="text-sm text-gray-700 list-disc list-inside space-y-1">
              <li>Audience: {app.audience || "seniors 64-75"}</li>
              <li>Geography: {app.geography || "—"}</li>
              <li>Do: large click-to-call, trust badges, plain language.</li>
              <li>Don&apos;t: government/Medicare logos, fine print as the main message, fear-based claims.</li>
            </ul>
          </section>

          <div className="text-[10px] text-gray-400 pt-6 border-t">Generated by medigap.plus · {app.businessName} media kit</div>
        </div>
      </div>
    </div>
  );
}
